# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField(default=datetime.date(2017, 4, 12))),
                ('age', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('General', 'General'), ('Dentist', 'Dentist'), ('Pharmacy', 'Pharmacy'), ('Physiotherapy', 'Physiotherapy')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
