# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20170413_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(default=datetime.date(2017, 4, 17)),
        ),
    ]
