# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0001_initial'),
        ('malaika', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2017, 4, 12))),
                ('doctors_comments', models.TextField()),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaika.Diagnose')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.Patient')),
            ],
        ),
    ]
