# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20170412_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaika.Diagnose'),
        ),
        migrations.DeleteModel(
            name='Diagnose',
        ),
    ]
