# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20170412_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='symptoms',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(default=datetime.date(2017, 4, 13)),
        ),
    ]
